In [ ]:
#HW 3A

In [93]:
import numpy as np
import pandas as pd
import random

In [ ]:
"""
The UCI “Default of Credit Card Clients” data set contains various fields
describing 30,000 credit card customers in Taiwan in 2005 (Yeh & Lien, doi://10.1016/j.eswa.2007.12.020).
"""

In [9]:
#Download the data and put it in a pandas dataframe
from sklearn.model_selection import train_test_split

In [6]:
%pip install xlrd

     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 96.5/96.5 kB 2.6 MB/s eta 0:00:00
Note: you may need to restart the kernel to use updated packages.


In [108]:
df = pd.read_excel("default.xls")

In [ ]:
"""
1: Split the data set 50/50 into a training set and test set.
"""

In [47]:
#Use the sklearn train test fxn to split evenly

In [109]:
df.dropna()
df.columns = df.iloc[0]
df.drop(index = df.index[0], axis = 0, inplace = True)

In [110]:
Y = df["default payment next month"]
X = df[["LIMIT_BAL", "SEX", "EDUCATION", "MARRIAGE", "AGE", "PAY_0", "PAY_2", "PAY_3", "PAY_4", "PAY_5", "PAY_6", "BILL_AMT1", "BILL_AMT2", "BILL_AMT3", "BILL_AMT4", "BILL_AMT5", "BILL_AMT6", "PAY_AMT1", "PAY_AMT2", "PAY_AMT3", "PAY_AMT4", "PAY_AMT5", "PAY_AMT6"]]

In [111]:
X_train, X_test, y_train, y_test = train_test_split(X,Y,random_state=random.randint(0,1000),test_size=.5,shuffle=True)

In [138]:
logs = [LogisticRegression().fit(
    np.reshape(X_train.iloc[:, i].values, (-1,1)),y_train.tolist())for i in range(len(X_train.columns))]

for i, log in enumerate(logs):
  print(X.columns[i] + ":")
  y_pred = log.predict(np.reshape(X_test.iloc[:, i].values, (-1,1)))
  print(metrics.confusion_matrix(y_test.tolist(), y_pred))
  print("Unbalanced Score: " + str(metrics.accuracy_score(y_test.tolist(), y_pred)))
  print("Balanced Score: " + str(metrics.balanced_accuracy_score(y_test.tolist(), y_pred)))
  print()

LIMIT_BAL:
[[11723     0]
 [ 3277     0]]
Unbalanced Score: 0.7815333333333333
Balanced Score: 0.5

SEX:
[[11723     0]
 [ 3277     0]]
Unbalanced Score: 0.7815333333333333
Balanced Score: 0.5

EDUCATION:
[[11723     0]
 [ 3277     0]]
Unbalanced Score: 0.7815333333333333
Balanced Score: 0.5

MARRIAGE:
[[11723     0]
 [ 3277     0]]
Unbalanced Score: 0.7815333333333333
Balanced Score: 0.5

AGE:
[[11723     0]
 [ 3277     0]]
Unbalanced Score: 0.7815333333333333
Balanced Score: 0.5

BILL_AMT1:
[[11723     0]
 [ 3277     0]]
Unbalanced Score: 0.7815333333333333
Balanced Score: 0.5

BILL_AMT2:
[[11446   277]
 [ 3207    70]]
Unbalanced Score: 0.7677333333333334
Balanced Score: 0.49886611847360196

BILL_AMT3:
[[11472   251]
 [ 3202    75]]
Unbalanced Score: 0.7698
Balanced Score: 0.5007379425244058

BILL_AMT4:
[[11723     0]
 [ 3277     0]]
Unbalanced Score: 0.7815333333333333
Balanced Score: 0.5

BILL_AMT5:
[[11458   265]
 [ 3216    61]]
Unbalanced Score: 0.7679333333333334
Balanced Score:

In [ ]:
#specific import statements

In [ ]:
"""
2: Logistic Regression

(a) Create several logistic regression models to predict default.payment.next.month (at least 10).
(b) Calculate the confusion matrices for each model based on the test set.
(c) Present a summary of the five models that gave the best overall accuracy on the test set. Which variables did you include, and which ones mattered the most?
"""

In [97]:
#specific import statements
from sklearn.linear_model import LogisticRegression
from sklearn import metrics

In [140]:
logs = [LogisticRegression().fit(
    np.reshape(X_train.iloc[:, i].values, (-1,1)),
    y_train.tolist())
    for i in range(len(X_train.columns))]
#log = LogisticRegression(max_iter = 1000).fit(X_train[], y_train)
for i, log in enumerate(logs):
  print(X.columns[i] + ":")
  y_pred = log.predict(np.reshape(X_test.iloc[:, i].values, (-1,1)))
  print(metrics.confusion_matrix(y_test.tolist(), y_pred))
  print("Unbalanced Score: " + str(metrics.accuracy_score(y_test.tolist(), y_pred)))
  print("Balanced Score: " + str(metrics.balanced_accuracy_score(y_test.tolist(), y_pred)))
  print()

LIMIT_BAL:
[[11723     0]
 [ 3277     0]]
Unbalanced Score: 0.7815333333333333
Balanced Score: 0.5

SEX:
[[11723     0]
 [ 3277     0]]
Unbalanced Score: 0.7815333333333333
Balanced Score: 0.5

EDUCATION:
[[11723     0]
 [ 3277     0]]
Unbalanced Score: 0.7815333333333333
Balanced Score: 0.5

MARRIAGE:
[[11723     0]
 [ 3277     0]]
Unbalanced Score: 0.7815333333333333
Balanced Score: 0.5

AGE:
[[11723     0]
 [ 3277     0]]
Unbalanced Score: 0.7815333333333333
Balanced Score: 0.5

BILL_AMT1:
[[11723     0]
 [ 3277     0]]
Unbalanced Score: 0.7815333333333333
Balanced Score: 0.5

BILL_AMT2:
[[11446   277]
 [ 3207    70]]
Unbalanced Score: 0.7677333333333334
Balanced Score: 0.49886611847360196

BILL_AMT3:
[[11472   251]
 [ 3202    75]]
Unbalanced Score: 0.7698
Balanced Score: 0.5007379425244058

BILL_AMT4:
[[11723     0]
 [ 3277     0]]
Unbalanced Score: 0.7815333333333333
Balanced Score: 0.5

BILL_AMT5:
[[11458   265]
 [ 3216    61]]
Unbalanced Score: 0.7679333333333334
Balanced Score:

In [143]:
#now i tried iterating through two columns each to see if it was any better at predicting. It wasn't :(

In [141]:
logs = [LogisticRegression().fit(
    np.reshape(X_train.iloc[:,i:i+1].values, (-1,1)),
    y_train.tolist())
    for i in range(len(X_train.columns))]
#log = LogisticRegression(max_iter = 1000).fit(X_train[], y_train)


In [142]:
for i, log in enumerate(logs):
  print(X.columns[i] + ":")
  y_pred = log.predict(np.reshape(X_test.iloc[:, i:i+1].values, (-1,1)))
  print(metrics.confusion_matrix(y_test.tolist(), y_pred))
  print("Unbalanced Score: " + str(metrics.accuracy_score(y_test.tolist(), y_pred)))
  print("Balanced Score: " + str(metrics.balanced_accuracy_score(y_test.tolist(), y_pred)))
  print()

LIMIT_BAL:
[[11723     0]
 [ 3277     0]]
Unbalanced Score: 0.7815333333333333
Balanced Score: 0.5

SEX:
[[11723     0]
 [ 3277     0]]
Unbalanced Score: 0.7815333333333333
Balanced Score: 0.5

EDUCATION:
[[11723     0]
 [ 3277     0]]
Unbalanced Score: 0.7815333333333333
Balanced Score: 0.5

MARRIAGE:
[[11723     0]
 [ 3277     0]]
Unbalanced Score: 0.7815333333333333
Balanced Score: 0.5

AGE:
[[11723     0]
 [ 3277     0]]
Unbalanced Score: 0.7815333333333333
Balanced Score: 0.5

BILL_AMT1:
[[11723     0]
 [ 3277     0]]
Unbalanced Score: 0.7815333333333333
Balanced Score: 0.5

BILL_AMT2:
[[11446   277]
 [ 3207    70]]
Unbalanced Score: 0.7677333333333334
Balanced Score: 0.49886611847360196

BILL_AMT3:
[[11472   251]
 [ 3202    75]]
Unbalanced Score: 0.7698
Balanced Score: 0.5007379425244058

BILL_AMT4:
[[11723     0]
 [ 3277     0]]
Unbalanced Score: 0.7815333333333333
Balanced Score: 0.5

BILL_AMT5:
[[11458   265]
 [ 3216    61]]
Unbalanced Score: 0.7679333333333334
Balanced Score:

In [ ]:
"""
3: Discriminant Analysis

(a) Predict default.payment.next.month using linear discriminant analysis. Calculate the confusion matrix on the test set.
(b) Predict default.payment.next.month using quadratic discriminant analysis. Calculate the confusion matrix on the test set.
"""

In [120]:
#specific import statements
from sklearn.discriminant_analysis import LinearDiscriminantAnalysis
from sklearn.discriminant_analysis import QuadraticDiscriminantAnalysis

In [121]:
LDA = LinearDiscriminantAnalysis()
QDA = QuadraticDiscriminantAnalysis()

In [129]:
linD = LDA.fit(X_train, y_train.to_list())
y_lin = LDA.predict(X_test)
print(metrics.confusion_matrix(y_test.tolist(), y_lin))
print("Unbalanced Score: " + str(metrics.accuracy_score(y_test.tolist(), y_lin)))
print("Balanced Score: " + str(metrics.balanced_accuracy_score(y_test.tolist(), y_lin)))


[[11723     0]
 [ 3277     0]]
Unbalanced Score: 0.7815333333333333
Balanced Score: 0.5
[[11723     0]
 [ 3277     0]]


In [128]:
quadD = QDA.fit(X_train, y_train.to_list())
y_quad = QDA.predict(X_test)
print(metrics.confusion_matrix(y_test.tolist(), y_quad))
print("Unbalanced Score: " + str(metrics.accuracy_score(y_test.tolist(), y_quad)))
print("Balanced Score: " + str(metrics.balanced_accuracy_score(y_test.tolist(), y_quad)))
print()

[[2600 9123]
 [ 366 2911]]
Unbalanced Score: 0.3674
Balanced Score: 0.5550493565604012



In [ ]:
"""
4: KNN Classifiers
(a) Create four different KNN classifiers to predict default.payment.next.month with four different values of k. 
    You will have to choose how to measure distance in a vector space that includes indicator variables and payment amounts ($NT 100k).
(b) Calculate the confusion matrices for each classifier based on the test set.

"""

In [130]:
#specific import statements
from sklearn.neighbors import KNeighborsClassifier

In [136]:
for i in range(1,10):
    print("Neighbors: " + str(i))
    KNN = KNeighborsClassifier(n_neighbors=i)
    k = KNN.fit(X_train, y_train.to_list())
    y_knn = KNN.predict(X_test)
    print(metrics.confusion_matrix(y_test.tolist(), y_knn))
    print("Unbalanced Score: " + str(metrics.accuracy_score(y_test.tolist(), y_knn)))
    print("Balanced Score: " + str(metrics.balanced_accuracy_score(y_test.tolist(), y_knn)))

Neighbors: 1
[[9440 2283]
 [2270 1007]]
Unbalanced Score: 0.6964666666666667
Balanced Score: 0.5562739418409455
Neighbors: 2
[[11135   588]
 [ 2910   367]]
Unbalanced Score: 0.7668
Balanced Score: 0.5309174333969062
Neighbors: 3
[[10294  1429]
 [ 2559   718]]
Unbalanced Score: 0.7341333333333333
Balanced Score: 0.5486028563261646
Neighbors: 4
[[11172   551]
 [ 2915   362]]
Unbalanced Score: 0.7689333333333334
Balanced Score: 0.531732634851519
Neighbors: 5
[[10688  1035]
 [ 2694   583]]
Unbalanced Score: 0.7514
Balanced Score: 0.5448093205090103
Neighbors: 6
[[11283   440]
 [ 2954   323]]
Unbalanced Score: 0.7737333333333334
Balanced Score: 0.5305163533441338
Neighbors: 7
[[10907   816]
 [ 2768   509]]
Unbalanced Score: 0.7610666666666667
Balanced Score: 0.5428591182106144
Neighbors: 8
[[11304   419]
 [ 2973   304]]
Unbalanced Score: 0.7738666666666667
Balanced Score: 0.5285130355312206
Neighbors: 9
[[11073   650]
 [ 2827   450]]
Unbalanced Score: 0.7682
Balanced Score: 0.54093708106130

In [ ]:
"""
5: Which of these classifiers would you recommend? You may make your recommendation based on any accuracy metric (not ncessarily the best overall accuracy).
"""

In [ ]:
"""
I would recommend KNN since it gave the highest balanced score.

"""